### ISSUE TITLE
[BUG] parameter not used in NewProcessor()

### ISSUE THREAD

**Issue by andy89923** [free5gc/pcf#27]
https://github.com/free5gc/pcf/blob/7df0d407bc38963bbe8568cd87f6f27ea197830c/internal/sbi/processor/processor.go#L17

**Comment by andy89923** [comment]
@HanHongChen

**Comment by HanHongChen** [comment]
@andy89923 please review [PR](https://github.com/free5gc/pcf/pull/30)
